### ISSUE TITLE
Use -q options for docker or docker inspect

### ISSUE THREAD

**Issue by robertu94** [nbulischeck/DCTF#3]
The output of the docker command are not designed to be scriptable/machine readable.  Using the -q option or docker inspect will be less likely to encounter weird errors.

**Comment by nbulischeck** [comment]
+1 for `docker inspect`. Didn't know that was a thing. Looks really neat.

The only problem with -q comes with removing containers that aren't ctf related which I heavily want to avoid.

**Comment by robertu94** [comment]
if you pair -q with --filter, you should be able to reliably filter by name or other features.

**Comment by nbulischeck** [comment]
@robertu94 Does that commit suffice?

**Comment by robertu94** [comment]
LGTM
