### ISSUE TITLE
Prefer ConfigParser.get() to a for loop

### ISSUE THREAD

**Issue by robertu94** [nbulischeck/DCTF#4]
ConfigParser allows for a .get() method which allow you to specify a default if a value does not exist.  This could be used to clean up lines 38 and following in ctf.py removing the forloop

**Comment by nbulischeck** [comment]
@robertu94 Closed?

**Comment by robertu94** [comment]
Close, you also don't need to explicitly None the values on each loop because it will be done by .get() anyway.
